# Generated by Django 3.0.3 on 2020-02-21 12:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_on',
            field=models.DateField(default=datetime.datetime(2020, 2, 24, 14, 23, 22, 748266)),
        ),
    ]
